# Generated by Django 5.1.1 on 2024-09-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
        ('user', '0016_remove_medic_age_remove_medic_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.IntegerField(verbose_name='prescription_number')),
                ('drugs', models.TextField(verbose_name='drugs')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='end_of_hospitalization',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='place_ofـhospitalization',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescribed_drugs',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='referralـtime',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='start_of_hospitalization',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='theـsubjectـofـillness',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='illnes_subject',
            field=models.CharField(default=1, max_length=255, verbose_name='illnes_subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='medic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_records', to='user.medic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_records', to='user.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='hospitalized',
            field=models.BooleanField(default=False, verbose_name='hospitalized'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='illness',
            field=models.TextField(verbose_name='illness'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_record', to='medical_records.prescription'),
        ),
    ]
