# Generated by Django 5.1.1 on 2024-09-28 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_prescription_and_more'),
        ('user', '0016_remove_medic_age_remove_medic_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('medic', 'patient')},
        ),
    ]
