# Generated by Django 5.1.1 on 2024-09-29 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_alter_medicalrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_record', to='medical_records.prescription'),
        ),
    ]
