# Generated by Django 5.1.1 on 2024-09-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0005_alter_prescription_prescription_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='related_file',
            field=models.FileField(null=True, upload_to='media/medical_records/', verbose_name='related_file'),
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medic',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='prescription',
        ),
    ]
