# Generated by Django 5.1.1 on 2024-09-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0006_alter_medicalrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='illnes_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='illnes_subject'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='illness',
            field=models.TextField(blank=True, null=True, verbose_name='illness'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='related_file',
            field=models.FileField(blank=True, null=True, upload_to='media/medical_records/', verbose_name='related_file'),
        ),
    ]
