# Generated by Django 5.1.1 on 2024-09-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_alter_medicalrecord_illnes_subject_and_more'),
        ('user', '0022_alter_medic_image_alter_timeslot_avg_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='medic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_patient', to='user.medic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medical_patient', to='user.patient'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='medicalrecord',
            unique_together={('patient', 'medic')},
        ),
    ]
