# Generated by Django 5.1.1 on 2024-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_prescription_remove_appointment_prescription_and_more'),
        ('medical_records', '0008_medicalrecord_medic_medicalrecord_patient_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
