# Generated by Django 5.1.1 on 2024-09-25 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_alter_timeslot_day_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255, verbose_name='description')),
                ('appointment_date', models.DateTimeField(verbose_name='appointment_date')),
                ('appointment_time', models.TimeField(verbose_name='appointment_time')),
                ('appointment_number', models.PositiveSmallIntegerField(verbose_name='appointment_time')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='user.patient')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='time', to='user.timeslot')),
            ],
        ),
    ]
