# Generated by Django 5.1.1 on 2024-09-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_remove_appointment_appointment_date_and_more'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment', to='medical_records.medicalrecord'),
        ),
    ]
