# Generated by Django 5.1.1 on 2024-09-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_medical_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='medical_record',
        ),
    ]
