# Generated by Django 5.1.1 on 2024-09-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_remove_appointment_medical_record'),
        ('medical_records', '0005_alter_prescription_prescription_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='medical_records.medicalrecord'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointment', to='medical_records.prescription'),
        ),
    ]
