# Generated by Django 5.1.1 on 2024-09-30 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_medical_record_appointment_prescription'),
        ('medical_records', '0007_alter_medicalrecord_illnes_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='medical_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appointments', to='medical_records.medicalrecord'),
        ),
    ]
