# Generated by Django 5.1.1 on 2024-10-01 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointment_medical_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(verbose_name='prescription_number')),
                ('drugs', models.TextField(verbose_name='drugs')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointment.prescription'),
            preserve_default=False,
        ),
    ]
