# Generated by Django 5.1.1 on 2024-10-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_prescription_remove_appointment_prescription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment',
            new_name='prescription',
        ),
    ]
