# Generated by Django 5.1.1 on 2024-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='address')),
                ('clinic_serial', models.PositiveIntegerField(unique=True, verbose_name='clinic_serial')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
            ],
        ),
    ]
