# Generated by Django 5.1.1 on 2024-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/clinics/', verbose_name='image'),
        ),
    ]
