# Generated by Django 5.1.1 on 2024-09-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_clinic_clinic_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='name'),
            preserve_default=False,
        ),
    ]
