# Generated by Django 5.1.1 on 2024-09-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
        ('user', '0008_alter_medic_age_alter_medic_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='clinic_address',
        ),
        migrations.AddField(
            model_name='medic',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='accepted'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_appointment', to='clinic.clinic'),
            preserve_default=False,
        ),
    ]
