# Generated by Django 5.1.1 on 2024-09-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_timeslot_clinic_address_medic_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='medical_system_number',
            field=models.CharField(max_length=20, verbose_name='medical_number'),
        ),
    ]
