# Generated by Django 5.1.1 on 2024-09-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_timeslot_avg_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='image',
            field=models.ImageField(default=1, upload_to='media/medics/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default=1, upload_to='media/patients/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
