# Generated by Django 5.1.1 on 2024-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_medic_image_patient_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='avg_patient_visit',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='avg_patient_visit'),
            preserve_default=False,
        ),
    ]
