# Generated by Django 5.1.1 on 2024-09-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_timeslot_avg_patient_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='day_of_week'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('medic', 'day_of_week')},
        ),
    ]
