# Generated by Django 5.1.1 on 2024-09-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_timeslot_is_active_user_is_medic_user_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medic',
            name='age',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='medic',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='last_name'),
        ),
    ]
