# Generated by Django 5.1.1 on 2024-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_timeslot_avg_patient_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='image',
            field=models.ImageField(null=True, upload_to='media/medics/', verbose_name='image'),
        ),
    ]
