# Generated by Django 5.1.1 on 2024-09-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_medic_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/medics/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='avg_visit_time',
            field=models.PositiveSmallIntegerField(verbose_name='avg_visit_time'),
        ),
    ]
